/*
 * MALPICA SOFT
 * VERSION 1.0
 * MARCOS VITUREIRA
 */
package malpica;

import javax.swing.ImageIcon;
import java.sql.*;
import java.io.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Vitureira
 */
public class Login extends javax.swing.JFrame {

    // Variables generales
    public String datoUsuario;
    public String datoUsuario1;
    public String datoClave;
    public String datoClave1;
    public String datoFechaOculta;
    public String datoDia;
    public String datoMes;
    public String datoAno;
    public int ID;

    public Login() {
        // Propiedades del frame
        initComponents();
        setLayout(null);
        setSize(640, 315);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/images/logos/logo.png")).getImage());

        // Métodos a ejecutar
        fecha();
        leerUsuario();
    }

    // Método para obtener la fecha actual
    public void fecha() {
        java.util.Date sistFecha = new java.util.Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YY");
        campoFechaOculta.setText(formato.format(sistFecha));

        datoFechaOculta = campoFechaOculta.getText().trim();
        datoDia = datoFechaOculta.charAt(0) + "" + datoFechaOculta.charAt(1);
        datoMes = datoFechaOculta.charAt(3) + "" + datoFechaOculta.charAt(4);
        datoAno = datoFechaOculta.charAt(6) + "" + datoFechaOculta.charAt(7);
        campoFechaOculta.setVisible(false);
    }
    
    // Método para leer el archivo "user.mvp" que contiene el usuario y la clave
    public void leerUsuario() {

        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;

        try {

            archivo = new File("user.mvp");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);

            String FilaLeida;
            String[] CadenaSeparada;

            while ((FilaLeida = br.readLine()) != null) {

                CadenaSeparada = FilaLeida.split("###");

                datoUsuario = CadenaSeparada[0];
                datoClave = CadenaSeparada[1];

                campoUsuario.setText(datoUsuario);
                campoClave.setText(datoClave);

                br.close();
                fr.close();
            }

        } catch (Exception e) {

        } finally {

            // Accion a realizar luego de leer el archivo
        }
    }

    // Método para guardar el archivo "user.mvp" que contiene el usuario y la clave
    public void guardarUsuario() {

        String cadenaDatos = "";
        cadenaDatos = datoUsuario + "###" + datoClave;

        FileWriter fichero;
        PrintWriter pw;

        try {

            fichero = new FileWriter("user.mvp", false); // true para que creen nuevas lineas
            pw = new PrintWriter(fichero);
            pw.println(cadenaDatos);
            pw.close();
            fichero.close();

        } catch (Exception e) {

            JOptionPane.showConfirmDialog(null, "Error al guardar los datos!", "Información", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    // Método setter para obtener el usuario en la clase Usuario
    public void setDatoUsuario(String datoUsuario1) {
        
        datoUsuario1 = campoUsuario.getText();
        this.datoUsuario1 = datoUsuario1;
    }
    
    // Método getter para obtener el usuario en la clase Usuario
    public String getDatoUsuario() {
        
        datoUsuario1 = campoUsuario.getText();
        return datoUsuario1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        panelFondoLogin = new javax.swing.JPanel();
        logoBienvenida = new javax.swing.JLabel();
        labelBienvenida = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoClave = new javax.swing.JPasswordField();
        logoUsuario = new javax.swing.JLabel();
        logoClave = new javax.swing.JLabel();
        fondoUsuario = new javax.swing.JLabel();
        fondoClave = new javax.swing.JLabel();
        checkRecordar = new javax.swing.JCheckBox();
        labelRecordar = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        botonIngresar = new javax.swing.JButton();
        fondoPanelLogin1 = new javax.swing.JLabel();
        fondoPanelLogin2 = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();
        campoFechaOculta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MS - Login");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 315));
        setResizable(false);
        getContentPane().setLayout(null);

        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelLogin.setPreferredSize(new java.awt.Dimension(640, 315));
        panelLogin.setLayout(null);

        panelFondoLogin.setMinimumSize(new java.awt.Dimension(740, 370));
        panelFondoLogin.setLayout(null);

        logoBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logos/logo-login.png"))); // NOI18N
        logoBienvenida.setText("jLabel1");
        panelFondoLogin.add(logoBienvenida);
        logoBienvenida.setBounds(90, 10, 50, 50);

        labelBienvenida.setFont(new java.awt.Font("Century", 0, 26)); // NOI18N
        labelBienvenida.setForeground(new java.awt.Color(255, 90, 0));
        labelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBienvenida.setText("MALPICA SOFT");
        labelBienvenida.setMaximumSize(new java.awt.Dimension(630, 40));
        labelBienvenida.setMinimumSize(new java.awt.Dimension(630, 40));
        labelBienvenida.setPreferredSize(new java.awt.Dimension(630, 40));
        panelFondoLogin.add(labelBienvenida);
        labelBienvenida.setBounds(150, 15, 210, 40);

        campoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        campoUsuario.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(175, 175, 175));
        campoUsuario.setText("Nombre de usuario");
        campoUsuario.setBorder(null);
        campoUsuario.setCaretColor(new java.awt.Color(175, 175, 175));
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusLost(evt);
            }
        });
        panelFondoLogin.add(campoUsuario);
        campoUsuario.setBounds(160, 75, 180, 30);

        campoClave.setBackground(new java.awt.Color(0, 0, 0));
        campoClave.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        campoClave.setForeground(new java.awt.Color(175, 175, 175));
        campoClave.setText("Clave de acceso");
        campoClave.setBorder(null);
        campoClave.setCaretColor(new java.awt.Color(175, 175, 175));
        campoClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoClaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoClaveFocusLost(evt);
            }
        });
        panelFondoLogin.add(campoClave);
        campoClave.setBounds(160, 125, 180, 30);

        logoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/usuario1.png"))); // NOI18N
        logoUsuario.setToolTipText("");
        panelFondoLogin.add(logoUsuario);
        logoUsuario.setBounds(105, 75, 30, 30);

        logoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/clave1.png"))); // NOI18N
        logoClave.setToolTipText("");
        panelFondoLogin.add(logoClave);
        logoClave.setBounds(105, 125, 30, 30);

        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login1.png"))); // NOI18N
        fondoUsuario.setText("jLabel1");
        panelFondoLogin.add(fondoUsuario);
        fondoUsuario.setBounds(85, 70, 280, 40);

        fondoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login1.png"))); // NOI18N
        fondoClave.setText("jLabel1");
        panelFondoLogin.add(fondoClave);
        fondoClave.setBounds(85, 120, 280, 40);

        checkRecordar.setForeground(new java.awt.Color(255, 180, 140));
        checkRecordar.setSelected(true);
        checkRecordar.setBorder(null);
        checkRecordar.setContentAreaFilled(false);
        checkRecordar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelFondoLogin.add(checkRecordar);
        checkRecordar.setBounds(160, 165, 20, 13);

        labelRecordar.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        labelRecordar.setForeground(new java.awt.Color(255, 90, 0));
        labelRecordar.setText("Recordar usuario");
        panelFondoLogin.add(labelRecordar);
        labelRecordar.setBounds(185, 166, 110, 20);

        botonCerrar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        botonCerrar.setForeground(new java.awt.Color(255, 180, 140));
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/boton1.png"))); // NOI18N
        botonCerrar.setText("CERRAR");
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/boton2.png"))); // NOI18N
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
        });
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        panelFondoLogin.add(botonCerrar);
        botonCerrar.setBounds(80, 195, 130, 35);

        botonIngresar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(255, 180, 140));
        botonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/boton1.png"))); // NOI18N
        botonIngresar.setText("INGRESAR");
        botonIngresar.setBorder(null);
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botones/boton2.png"))); // NOI18N
        botonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIngresarMouseExited(evt);
            }
        });
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });
        panelFondoLogin.add(botonIngresar);
        botonIngresar.setBounds(240, 195, 130, 35);

        fondoPanelLogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/varios/cuadro5.png"))); // NOI18N
        fondoPanelLogin1.setToolTipText("");
        panelFondoLogin.add(fondoPanelLogin1);
        fondoPanelLogin1.setBounds(0, 0, 450, 250);

        fondoPanelLogin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoPanelLogin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos/fondo7.jpg"))); // NOI18N
        fondoPanelLogin2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelFondoLogin.add(fondoPanelLogin2);
        fondoPanelLogin2.setBounds(-90, -32, 640, 315);

        panelLogin.add(panelFondoLogin);
        panelFondoLogin.setBounds(90, 32, 450, 250);

        fondoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos/fondo7.jpg"))); // NOI18N
        fondoLogin.setToolTipText("");
        fondoLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fondoLogin.setRequestFocusEnabled(false);
        panelLogin.add(fondoLogin);
        fondoLogin.setBounds(0, 0, 640, 315);
        panelLogin.add(campoFechaOculta);
        campoFechaOculta.setBounds(10, 10, 90, 20);

        getContentPane().add(panelLogin);
        panelLogin.setBounds(0, 0, 640, 315);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        botonCerrar.setForeground(new java.awt.Color(255, 90, 0));
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        botonCerrar.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_botonCerrarMouseExited

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseEntered
        botonIngresar.setForeground(new java.awt.Color(255, 90, 0));
    }//GEN-LAST:event_botonIngresarMouseEntered

    private void botonIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarMouseExited
        botonIngresar.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_botonIngresarMouseExited

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        datoUsuario = campoUsuario.getText().trim();
        datoUsuario1 = campoUsuario.getText().trim();
        datoClave = campoClave.getText().trim();
        datoClave1 = campoClave.getText().trim();
        
        // Si los campos solicitados no están vacíos, que siga con el try
        if (!datoUsuario.equals("") && !datoClave.equals("")) {

            // Establezco conexión con db para consultar si coinciden los datos
            try {

                Connection con = Conexion.conectar();
                PreparedStatement sta = con.prepareStatement("select * from base where usuario = '" + datoUsuario + "' and "
                        + "clave = '" + datoClave + "'");
                ResultSet res = sta.executeQuery();

                // Si el usuario y la contraseña es válida continúa
                if (res.next()) {

                    ID = res.getInt("id");

                    // Si el checkbox de "Recordar Usuario" se activa, bloquea los campos y viceversa
                    if (checkRecordar.isSelected()) {

                        guardarUsuario();

                    } else {

                        datoUsuario = "";
                        datoClave = "";
                        guardarUsuario();
                    }

                    // Actualiza la fecha de logueo en la base
                    Connection con1 = Conexion.conectar();
                    PreparedStatement sta1 = con1.prepareStatement("update base set fecha_ingreso=?, dia_ingreso=?, "
                            + "mes_ingreso=?, ano_ingreso=? where id = '" + ID + "'");

                    sta1.setString(1, datoFechaOculta);
                    sta1.setString(2, datoDia);
                    sta1.setString(3, datoMes);
                    sta1.setString(4, datoAno);

                    sta1.executeUpdate();
                    con1.close();
                    con.close();

                    new Inicio().setVisible(true);
                    this.dispose();

                } else {

                    JOptionPane.showConfirmDialog(null, "POR FAVOR, REVISE LOS DATOS INGRESADOS!", "Información", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);

                    con.close();
                }

            } catch (SQLException e) {

                JOptionPane.showConfirmDialog(null, "Error de conexión!", "Información", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }

        } else {

            JOptionPane.showConfirmDialog(null, "POR FAVOR, REVISE LOS DATOS INGRESADOS!", "Información", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
        campoUsuario.setForeground(new java.awt.Color(255, 180, 140));
        campoClave.setForeground(new java.awt.Color(175, 175, 175));
        logoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/usuario2.png")));
        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login2.png")));
        logoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/clave1.png")));
        fondoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login1.png")));

        if (campoUsuario.getText().equals("Nombre de usuario")) {

            campoUsuario.setText("");
        }
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusLost
        campoUsuario.setForeground(new java.awt.Color(175, 175, 175));
        logoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/usuario1.png")));
        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login1.png")));

        if (campoUsuario.getText().equals("")) {

            campoUsuario.setText("Nombre de usuario");
        }
    }//GEN-LAST:event_campoUsuarioFocusLost

    private void campoClaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoClaveFocusGained
        campoClave.setForeground(new java.awt.Color(255, 180, 140));
        campoUsuario.setForeground(new java.awt.Color(175, 175, 175));
        logoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/clave2.png")));
        fondoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login2.png")));
        logoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/usuario1.png")));
        fondoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login1.png")));

        if (campoClave.getText().equals("Clave de acceso")) {

            campoClave.setText("");
        }
    }//GEN-LAST:event_campoClaveFocusGained

    private void campoClaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoClaveFocusLost
        campoClave.setForeground(new java.awt.Color(175, 175, 175));
        logoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/clave1.png")));
        fondoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/campos/campo-login1.png")));

        if (campoClave.getText().equals("")) {

            campoClave.setText("Clave de acceso");
        }
    }//GEN-LAST:event_campoClaveFocusLost

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPasswordField campoClave;
    private javax.swing.JTextField campoFechaOculta;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JCheckBox checkRecordar;
    private javax.swing.JLabel fondoClave;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JLabel fondoPanelLogin1;
    private javax.swing.JLabel fondoPanelLogin2;
    private javax.swing.JLabel fondoUsuario;
    private javax.swing.JLabel labelBienvenida;
    private javax.swing.JLabel labelRecordar;
    private javax.swing.JLabel logoBienvenida;
    private javax.swing.JLabel logoClave;
    private javax.swing.JLabel logoUsuario;
    private javax.swing.JPanel panelFondoLogin;
    private javax.swing.JPanel panelLogin;
    // End of variables declaration//GEN-END:variables
}
