/*
 * MALPICA SOFT
 * VERSION 1.0
 * MARCOS VITUREIRA
 */
package malpica;

import javax.swing.ImageIcon;
import stock.*;
import compras.*;
import ventas.*;
import gastos.*;
import clientes.*;
import proveedores.*;

/**
 *
 * @author Marcos Vitureira
 */
public class Inicio extends javax.swing.JFrame {

    // Variables del mouse
    int xMouse;
    int yMouse;
    
    public Inicio() {
        // Propiedades del frame
        initComponents();
        setLayout(null);
        setSize(800, 398);
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/images/logos/logo.png")).getImage());
        
        // Métodos a ejecutar
        ocultarPaneles();
    }
    
    // Método para ocultar los paneles del menú principal
    public void ocultarPaneles(){
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        labelCompras = new javax.swing.JLabel();
        labelVentas = new javax.swing.JLabel();
        labelGastos = new javax.swing.JLabel();
        labelClientes = new javax.swing.JLabel();
        labelProveedores = new javax.swing.JLabel();
        labelReportes = new javax.swing.JLabel();
        labelAyuda = new javax.swing.JLabel();
        labelMinimizar = new javax.swing.JLabel();
        labelCerrar = new javax.swing.JLabel();
        fondoMenu = new javax.swing.JLabel();
        panelStock = new javax.swing.JPanel();
        labelIngresarProd = new javax.swing.JLabel();
        labelConsultarProd = new javax.swing.JLabel();
        labelModificarProd = new javax.swing.JLabel();
        labelEliminarProd = new javax.swing.JLabel();
        panelCompras = new javax.swing.JPanel();
        labelIngresarComp = new javax.swing.JLabel();
        labelConsultarComp = new javax.swing.JLabel();
        labelModificarComp = new javax.swing.JLabel();
        labelEliminarComp = new javax.swing.JLabel();
        panelVentas = new javax.swing.JPanel();
        labelIngresarVent = new javax.swing.JLabel();
        labelConsultarVent = new javax.swing.JLabel();
        labelModificarVent = new javax.swing.JLabel();
        labelEliminarVent = new javax.swing.JLabel();
        panelGastos = new javax.swing.JPanel();
        labelIngresarGast = new javax.swing.JLabel();
        labelConsultarGast = new javax.swing.JLabel();
        labelModificarGast = new javax.swing.JLabel();
        labelEliminarGast = new javax.swing.JLabel();
        panelClientes = new javax.swing.JPanel();
        labelIngresarClie = new javax.swing.JLabel();
        labelConsultarClie = new javax.swing.JLabel();
        labelModificarClie = new javax.swing.JLabel();
        labelEliminarClie = new javax.swing.JLabel();
        panelProveedores = new javax.swing.JPanel();
        labelIngresarProv = new javax.swing.JLabel();
        labelConsultarProv = new javax.swing.JLabel();
        labelModificarProv = new javax.swing.JLabel();
        labelEliminarProv = new javax.swing.JLabel();
        fondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Malpica Soft");
        setMaximumSize(new java.awt.Dimension(800, 398));
        setMinimumSize(new java.awt.Dimension(800, 398));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        panelInicio.setMaximumSize(new java.awt.Dimension(800, 368));
        panelInicio.setMinimumSize(new java.awt.Dimension(800, 368));
        panelInicio.setPreferredSize(new java.awt.Dimension(800, 368));
        panelInicio.setLayout(null);

        panelMenu.setLayout(null);

        labelUsuario.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setText("USUARIO");
        labelUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUsuarioMouseExited(evt);
            }
        });
        panelMenu.add(labelUsuario);
        labelUsuario.setBounds(10, 0, 56, 30);

        labelStock.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelStock.setText("STOCK");
        labelStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelStockMouseExited(evt);
            }
        });
        panelMenu.add(labelStock);
        labelStock.setBounds(76, 0, 40, 30);

        labelCompras.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setText("COMPRAS");
        labelCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelComprasMouseExited(evt);
            }
        });
        panelMenu.add(labelCompras);
        labelCompras.setBounds(126, 0, 62, 30);

        labelVentas.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setText("VENTAS");
        labelVentas.setToolTipText("");
        labelVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelVentasMouseExited(evt);
            }
        });
        panelMenu.add(labelVentas);
        labelVentas.setBounds(198, 0, 49, 30);

        labelGastos.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setText("GASTOS");
        labelGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelGastosMouseExited(evt);
            }
        });
        panelMenu.add(labelGastos);
        labelGastos.setBounds(257, 0, 49, 30);

        labelClientes.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setText("CLIENTES");
        labelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelClientesMouseExited(evt);
            }
        });
        panelMenu.add(labelClientes);
        labelClientes.setBounds(316, 0, 56, 30);

        labelProveedores.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setText("PROVEEDORES");
        labelProveedores.setToolTipText("");
        labelProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelProveedoresMouseExited(evt);
            }
        });
        panelMenu.add(labelProveedores);
        labelProveedores.setBounds(382, 0, 90, 30);

        labelReportes.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setText("REPORTES");
        labelReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelReportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelReportesMouseExited(evt);
            }
        });
        panelMenu.add(labelReportes);
        labelReportes.setBounds(482, 0, 65, 30);

        labelAyuda.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setText("AYUDA");
        labelAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAyudaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAyudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAyudaMouseExited(evt);
            }
        });
        panelMenu.add(labelAyuda);
        labelAyuda.setBounds(557, 0, 43, 30);

        labelMinimizar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/minimizar.png"))); // NOI18N
        labelMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMinimizarMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinimizarMouseClicked(evt);
            }
        });
        panelMenu.add(labelMinimizar);
        labelMinimizar.setBounds(735, 0, 30, 30);

        labelCerrar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/cerrar.png"))); // NOI18N
        labelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelCerrarMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCerrarMouseClicked(evt);
            }
        });
        panelMenu.add(labelCerrar);
        labelCerrar.setBounds(765, 0, 30, 30);

        fondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/varios/barramenu.png"))); // NOI18N
        fondoMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMenuMouseDragged(evt);
            }
        });
        fondoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMenuMousePressed(evt);
            }
        });
        panelMenu.add(fondoMenu);
        fondoMenu.setBounds(0, 0, 800, 30);

        panelInicio.add(panelMenu);
        panelMenu.setBounds(0, 0, 800, 30);

        panelStock.setBackground(new java.awt.Color(20, 20, 20));
        panelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelStockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelStockMouseExited(evt);
            }
        });
        panelStock.setLayout(null);

        labelIngresarProd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelIngresarProd.setForeground(new java.awt.Color(175, 175, 175));
        labelIngresarProd.setText("Ingresar productos");
        labelIngresarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIngresarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIngresarProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIngresarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIngresarProdMouseExited(evt);
            }
        });
        panelStock.add(labelIngresarProd);
        labelIngresarProd.setBounds(10, 10, 120, 17);

        labelConsultarProd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelConsultarProd.setForeground(new java.awt.Color(175, 175, 175));
        labelConsultarProd.setText("Consultar productos");
        labelConsultarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelConsultarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConsultarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConsultarProdMouseExited(evt);
            }
        });
        panelStock.add(labelConsultarProd);
        labelConsultarProd.setBounds(10, 40, 120, 17);

        labelModificarProd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelModificarProd.setForeground(new java.awt.Color(175, 175, 175));
        labelModificarProd.setText("Modificar productos");
        labelModificarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarProdMouseExited(evt);
            }
        });
        panelStock.add(labelModificarProd);
        labelModificarProd.setBounds(10, 70, 120, 17);

        labelEliminarProd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelEliminarProd.setForeground(new java.awt.Color(175, 175, 175));
        labelEliminarProd.setText("Eliminar productos");
        labelEliminarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarProdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarProdMouseExited(evt);
            }
        });
        panelStock.add(labelEliminarProd);
        labelEliminarProd.setBounds(10, 100, 120, 17);

        panelInicio.add(panelStock);
        panelStock.setBounds(76, 30, 140, 130);

        panelCompras.setBackground(new java.awt.Color(20, 20, 20));
        panelCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelComprasMouseExited(evt);
            }
        });
        panelCompras.setLayout(null);

        labelIngresarComp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelIngresarComp.setForeground(new java.awt.Color(175, 175, 175));
        labelIngresarComp.setText("Ingresar compras");
        labelIngresarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIngresarComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIngresarCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIngresarCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIngresarCompMouseExited(evt);
            }
        });
        panelCompras.add(labelIngresarComp);
        labelIngresarComp.setBounds(10, 10, 110, 17);

        labelConsultarComp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelConsultarComp.setForeground(new java.awt.Color(175, 175, 175));
        labelConsultarComp.setText("Consultar compras");
        labelConsultarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelConsultarComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConsultarCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConsultarCompMouseExited(evt);
            }
        });
        panelCompras.add(labelConsultarComp);
        labelConsultarComp.setBounds(10, 40, 110, 17);

        labelModificarComp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelModificarComp.setForeground(new java.awt.Color(175, 175, 175));
        labelModificarComp.setText("Modificar compras");
        labelModificarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarCompMouseExited(evt);
            }
        });
        panelCompras.add(labelModificarComp);
        labelModificarComp.setBounds(10, 70, 110, 17);

        labelEliminarComp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelEliminarComp.setForeground(new java.awt.Color(175, 175, 175));
        labelEliminarComp.setText("Eliminar compras");
        labelEliminarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminarComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarCompMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarCompMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarCompMouseExited(evt);
            }
        });
        panelCompras.add(labelEliminarComp);
        labelEliminarComp.setBounds(10, 100, 110, 17);

        panelInicio.add(panelCompras);
        panelCompras.setBounds(126, 30, 130, 130);

        panelVentas.setBackground(new java.awt.Color(20, 20, 20));
        panelVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelVentasMouseExited(evt);
            }
        });
        panelVentas.setLayout(null);

        labelIngresarVent.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelIngresarVent.setForeground(new java.awt.Color(175, 175, 175));
        labelIngresarVent.setText("Ingresar ventas");
        labelIngresarVent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIngresarVent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIngresarVentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIngresarVentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIngresarVentMouseExited(evt);
            }
        });
        panelVentas.add(labelIngresarVent);
        labelIngresarVent.setBounds(10, 10, 100, 17);

        labelConsultarVent.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelConsultarVent.setForeground(new java.awt.Color(175, 175, 175));
        labelConsultarVent.setText("Consultar ventas");
        labelConsultarVent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelConsultarVent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarVentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConsultarVentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConsultarVentMouseExited(evt);
            }
        });
        panelVentas.add(labelConsultarVent);
        labelConsultarVent.setBounds(10, 40, 100, 17);

        labelModificarVent.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelModificarVent.setForeground(new java.awt.Color(175, 175, 175));
        labelModificarVent.setText("Modificar ventas");
        labelModificarVent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarVent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarVentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarVentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarVentMouseExited(evt);
            }
        });
        panelVentas.add(labelModificarVent);
        labelModificarVent.setBounds(10, 70, 100, 17);

        labelEliminarVent.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelEliminarVent.setForeground(new java.awt.Color(175, 175, 175));
        labelEliminarVent.setText("Eliminar ventas");
        labelEliminarVent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminarVent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarVentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarVentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarVentMouseExited(evt);
            }
        });
        panelVentas.add(labelEliminarVent);
        labelEliminarVent.setBounds(10, 100, 100, 17);

        panelInicio.add(panelVentas);
        panelVentas.setBounds(198, 30, 120, 130);

        panelGastos.setBackground(new java.awt.Color(20, 20, 20));
        panelGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGastosMouseExited(evt);
            }
        });
        panelGastos.setLayout(null);

        labelIngresarGast.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelIngresarGast.setForeground(new java.awt.Color(175, 175, 175));
        labelIngresarGast.setText("Ingresar gastos");
        labelIngresarGast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIngresarGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIngresarGastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIngresarGastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIngresarGastMouseExited(evt);
            }
        });
        panelGastos.add(labelIngresarGast);
        labelIngresarGast.setBounds(10, 10, 100, 17);

        labelConsultarGast.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelConsultarGast.setForeground(new java.awt.Color(175, 175, 175));
        labelConsultarGast.setText("Consultar gastos");
        labelConsultarGast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelConsultarGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarGastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConsultarGastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConsultarGastMouseExited(evt);
            }
        });
        panelGastos.add(labelConsultarGast);
        labelConsultarGast.setBounds(10, 40, 100, 17);

        labelModificarGast.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelModificarGast.setForeground(new java.awt.Color(175, 175, 175));
        labelModificarGast.setText("Modificar gastos");
        labelModificarGast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarGastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarGastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarGastMouseExited(evt);
            }
        });
        panelGastos.add(labelModificarGast);
        labelModificarGast.setBounds(10, 70, 100, 17);

        labelEliminarGast.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelEliminarGast.setForeground(new java.awt.Color(175, 175, 175));
        labelEliminarGast.setText("Eliminar gastos");
        labelEliminarGast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminarGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarGastMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarGastMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarGastMouseExited(evt);
            }
        });
        panelGastos.add(labelEliminarGast);
        labelEliminarGast.setBounds(10, 100, 100, 17);

        panelInicio.add(panelGastos);
        panelGastos.setBounds(257, 30, 120, 130);

        panelClientes.setBackground(new java.awt.Color(20, 20, 20));
        panelClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelClientesMouseExited(evt);
            }
        });
        panelClientes.setLayout(null);

        labelIngresarClie.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelIngresarClie.setForeground(new java.awt.Color(175, 175, 175));
        labelIngresarClie.setText("Ingresar clientes");
        labelIngresarClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIngresarClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIngresarClieMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIngresarClieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIngresarClieMouseExited(evt);
            }
        });
        panelClientes.add(labelIngresarClie);
        labelIngresarClie.setBounds(10, 10, 100, 17);

        labelConsultarClie.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelConsultarClie.setForeground(new java.awt.Color(175, 175, 175));
        labelConsultarClie.setText("Consultar clientes");
        labelConsultarClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelConsultarClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarClieMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConsultarClieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConsultarClieMouseExited(evt);
            }
        });
        panelClientes.add(labelConsultarClie);
        labelConsultarClie.setBounds(10, 40, 100, 17);

        labelModificarClie.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelModificarClie.setForeground(new java.awt.Color(175, 175, 175));
        labelModificarClie.setText("Modificar clientes");
        labelModificarClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarClieMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarClieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarClieMouseExited(evt);
            }
        });
        panelClientes.add(labelModificarClie);
        labelModificarClie.setBounds(10, 70, 100, 17);

        labelEliminarClie.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelEliminarClie.setForeground(new java.awt.Color(175, 175, 175));
        labelEliminarClie.setText("Eliminar clientes");
        labelEliminarClie.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminarClie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarClieMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarClieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarClieMouseExited(evt);
            }
        });
        panelClientes.add(labelEliminarClie);
        labelEliminarClie.setBounds(10, 100, 100, 17);

        panelInicio.add(panelClientes);
        panelClientes.setBounds(316, 30, 130, 130);

        panelProveedores.setBackground(new java.awt.Color(20, 20, 20));
        panelProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProveedoresMouseExited(evt);
            }
        });
        panelProveedores.setLayout(null);

        labelIngresarProv.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelIngresarProv.setForeground(new java.awt.Color(175, 175, 175));
        labelIngresarProv.setText("Ingresar proveedores");
        labelIngresarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIngresarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIngresarProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelIngresarProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelIngresarProvMouseExited(evt);
            }
        });
        panelProveedores.add(labelIngresarProv);
        labelIngresarProv.setBounds(10, 10, 130, 17);

        labelConsultarProv.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelConsultarProv.setForeground(new java.awt.Color(175, 175, 175));
        labelConsultarProv.setText("Consultar proveedores");
        labelConsultarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelConsultarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelConsultarProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelConsultarProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelConsultarProvMouseExited(evt);
            }
        });
        panelProveedores.add(labelConsultarProv);
        labelConsultarProv.setBounds(10, 40, 130, 17);

        labelModificarProv.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelModificarProv.setForeground(new java.awt.Color(175, 175, 175));
        labelModificarProv.setText("Modificar proveedores");
        labelModificarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelModificarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelModificarProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelModificarProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelModificarProvMouseExited(evt);
            }
        });
        panelProveedores.add(labelModificarProv);
        labelModificarProv.setBounds(10, 70, 130, 17);

        labelEliminarProv.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        labelEliminarProv.setForeground(new java.awt.Color(175, 175, 175));
        labelEliminarProv.setText("Eliminar proveedores");
        labelEliminarProv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelEliminarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarProvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelEliminarProvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEliminarProvMouseExited(evt);
            }
        });
        panelProveedores.add(labelEliminarProv);
        labelEliminarProv.setBounds(10, 100, 130, 17);

        panelInicio.add(panelProveedores);
        panelProveedores.setBounds(382, 30, 150, 130);

        fondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondos/fondo1.png"))); // NOI18N
        fondoInicio.setText("jLabel1");
        fondoInicio.setMaximumSize(new java.awt.Dimension(800, 368));
        fondoInicio.setMinimumSize(new java.awt.Dimension(800, 368));
        fondoInicio.setPreferredSize(new java.awt.Dimension(800, 368));
        fondoInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoInicioMouseClicked(evt);
            }
        });
        panelInicio.add(fondoInicio);
        fondoInicio.setBounds(0, 30, 800, 368);

        getContentPane().add(panelInicio);
        panelInicio.setBounds(0, 0, 800, 398);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fondoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMenuMousePressed
        // Movimiento del frame
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_fondoMenuMousePressed

    private void fondoMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMenuMouseDragged
        // Movimiento del frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_fondoMenuMouseDragged

    private void labelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_labelCerrarMouseClicked

    private void labelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseEntered
        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/cerrar1.png")));
    }//GEN-LAST:event_labelCerrarMouseEntered

    private void labelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCerrarMouseExited
        labelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/cerrar.png")));
    }//GEN-LAST:event_labelCerrarMouseExited

    private void labelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_labelMinimizarMouseClicked

    private void labelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizarMouseEntered
        labelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/minimizar1.png")));
    }//GEN-LAST:event_labelMinimizarMouseEntered

    private void labelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinimizarMouseExited
        labelMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos/minimizar.png")));
    }//GEN-LAST:event_labelMinimizarMouseExited

    private void labelUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsuarioMouseEntered
        labelUsuario.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelUsuarioMouseEntered

    private void labelUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsuarioMouseExited
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_labelUsuarioMouseExited

    private void labelStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelStockMouseEntered
        labelStock.setForeground(new java.awt.Color(255, 90, 0));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelStock.setVisible(true);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelStockMouseEntered

    private void labelStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelStockMouseExited
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        panelStock.setVisible(false);
    }//GEN-LAST:event_labelStockMouseExited

    private void labelComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelComprasMouseEntered
        labelCompras.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelCompras.setVisible(true);
        panelStock.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelComprasMouseEntered

    private void labelComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelComprasMouseExited
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        panelCompras.setVisible(false);
    }//GEN-LAST:event_labelComprasMouseExited

    private void labelVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVentasMouseEntered
        labelVentas.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelVentas.setVisible(true);
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelVentasMouseEntered

    private void labelVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelVentasMouseExited
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        panelVentas.setVisible(false);
    }//GEN-LAST:event_labelVentasMouseExited

    private void labelGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGastosMouseEntered
        labelGastos.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelGastos.setVisible(true);
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelGastosMouseEntered

    private void labelGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGastosMouseExited
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        panelGastos.setVisible(false);
    }//GEN-LAST:event_labelGastosMouseExited

    private void labelClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClientesMouseEntered
        labelClientes.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelClientes.setVisible(true);
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelClientesMouseEntered

    private void labelClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelClientesMouseExited
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        panelClientes.setVisible(false);
    }//GEN-LAST:event_labelClientesMouseExited

    private void labelProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelProveedoresMouseEntered
        labelProveedores.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
        panelProveedores.setVisible(true);
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
    }//GEN-LAST:event_labelProveedoresMouseEntered

    private void labelProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelProveedoresMouseExited
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_labelProveedoresMouseExited

    private void labelReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportesMouseEntered
        labelReportes.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_labelReportesMouseEntered

    private void labelReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportesMouseExited
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_labelReportesMouseExited

    private void labelAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAyudaMouseEntered
        labelAyuda.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_labelAyudaMouseEntered

    private void labelAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAyudaMouseExited
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_labelAyudaMouseExited

    private void panelStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStockMouseEntered
        labelStock.setForeground(new java.awt.Color(255, 90, 0));
        panelStock.setVisible(true);
    }//GEN-LAST:event_panelStockMouseEntered

    private void panelStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelStockMouseExited
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        panelStock.setVisible(false);
    }//GEN-LAST:event_panelStockMouseExited

    private void panelComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComprasMouseEntered
        labelCompras.setForeground(new java.awt.Color(255, 90, 0));
        panelCompras.setVisible(true);
    }//GEN-LAST:event_panelComprasMouseEntered

    private void panelComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComprasMouseExited
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        panelCompras.setVisible(false);
    }//GEN-LAST:event_panelComprasMouseExited

    private void panelVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentasMouseEntered
        labelVentas.setForeground(new java.awt.Color(255, 90, 0));
        panelVentas.setVisible(true);
    }//GEN-LAST:event_panelVentasMouseEntered

    private void panelVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVentasMouseExited
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        panelVentas.setVisible(false);
    }//GEN-LAST:event_panelVentasMouseExited

    private void panelGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGastosMouseEntered
        labelGastos.setForeground(new java.awt.Color(255, 90, 0));
        panelGastos.setVisible(true);
    }//GEN-LAST:event_panelGastosMouseEntered

    private void panelGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGastosMouseExited
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        panelGastos.setVisible(false);
    }//GEN-LAST:event_panelGastosMouseExited

    private void panelClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClientesMouseEntered
        labelClientes.setForeground(new java.awt.Color(255, 90, 0));
        panelClientes.setVisible(true);
    }//GEN-LAST:event_panelClientesMouseEntered

    private void panelClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelClientesMouseExited
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        panelClientes.setVisible(false);
    }//GEN-LAST:event_panelClientesMouseExited

    private void panelProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProveedoresMouseEntered
        labelProveedores.setForeground(new java.awt.Color(255, 90, 0));
        panelProveedores.setVisible(true);
    }//GEN-LAST:event_panelProveedoresMouseEntered

    private void panelProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProveedoresMouseExited
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        panelProveedores.setVisible(false);
    }//GEN-LAST:event_panelProveedoresMouseExited

    private void labelIngresarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarProdMouseEntered
        labelIngresarProd.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 90, 0));
        panelStock.setVisible(true);
    }//GEN-LAST:event_labelIngresarProdMouseEntered

    private void labelIngresarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarProdMouseExited
        labelIngresarProd.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelIngresarProdMouseExited

    private void labelConsultarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarProdMouseEntered
        labelConsultarProd.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 90, 0));
        panelStock.setVisible(true);
    }//GEN-LAST:event_labelConsultarProdMouseEntered

    private void labelConsultarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarProdMouseExited
        labelConsultarProd.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelConsultarProdMouseExited

    private void labelModificarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarProdMouseEntered
        labelModificarProd.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 90, 0));
        panelStock.setVisible(true);
    }//GEN-LAST:event_labelModificarProdMouseEntered

    private void labelModificarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarProdMouseExited
        labelModificarProd.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelModificarProdMouseExited

    private void labelEliminarProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarProdMouseEntered
        labelEliminarProd.setForeground(new java.awt.Color(255, 90, 0));
        labelStock.setForeground(new java.awt.Color(255, 90, 0));
        panelStock.setVisible(true);
    }//GEN-LAST:event_labelEliminarProdMouseEntered

    private void labelEliminarProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarProdMouseExited
        labelEliminarProd.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelEliminarProdMouseExited

    private void labelIngresarCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarCompMouseEntered
        labelIngresarComp.setForeground(new java.awt.Color(255, 90, 0));
        labelCompras.setForeground(new java.awt.Color(255, 90, 0));
        panelCompras.setVisible(true);
    }//GEN-LAST:event_labelIngresarCompMouseEntered

    private void labelIngresarCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarCompMouseExited
        labelIngresarComp.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelIngresarCompMouseExited

    private void labelConsultarCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarCompMouseEntered
        labelConsultarComp.setForeground(new java.awt.Color(255, 90, 0));
        labelCompras.setForeground(new java.awt.Color(255, 90, 0));
        panelCompras.setVisible(true);
    }//GEN-LAST:event_labelConsultarCompMouseEntered

    private void labelConsultarCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarCompMouseExited
        labelConsultarComp.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelConsultarCompMouseExited

    private void labelModificarCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarCompMouseEntered
        labelModificarComp.setForeground(new java.awt.Color(255, 90, 0));
        labelCompras.setForeground(new java.awt.Color(255, 90, 0));
        panelCompras.setVisible(true);
    }//GEN-LAST:event_labelModificarCompMouseEntered

    private void labelModificarCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarCompMouseExited
        labelModificarComp.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelModificarCompMouseExited

    private void labelEliminarCompMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarCompMouseEntered
        labelEliminarComp.setForeground(new java.awt.Color(255, 90, 0));
        labelCompras.setForeground(new java.awt.Color(255, 90, 0));
        panelCompras.setVisible(true);
    }//GEN-LAST:event_labelEliminarCompMouseEntered

    private void labelEliminarCompMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarCompMouseExited
        labelEliminarComp.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelEliminarCompMouseExited

    private void labelIngresarVentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarVentMouseEntered
        labelIngresarVent.setForeground(new java.awt.Color(255, 90, 0));
        labelVentas.setForeground(new java.awt.Color(255, 90, 0));
        panelVentas.setVisible(true);
    }//GEN-LAST:event_labelIngresarVentMouseEntered

    private void labelIngresarVentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarVentMouseExited
        labelIngresarVent.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelIngresarVentMouseExited

    private void labelConsultarVentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarVentMouseEntered
        labelConsultarVent.setForeground(new java.awt.Color(255, 90, 0));
        labelVentas.setForeground(new java.awt.Color(255, 90, 0));
        panelVentas.setVisible(true);
    }//GEN-LAST:event_labelConsultarVentMouseEntered

    private void labelConsultarVentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarVentMouseExited
        labelConsultarVent.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelConsultarVentMouseExited

    private void labelModificarVentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarVentMouseEntered
        labelModificarVent.setForeground(new java.awt.Color(255, 90, 0));
        labelVentas.setForeground(new java.awt.Color(255, 90, 0));
        panelVentas.setVisible(true);
    }//GEN-LAST:event_labelModificarVentMouseEntered

    private void labelModificarVentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarVentMouseExited
        labelModificarVent.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelModificarVentMouseExited

    private void labelEliminarVentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarVentMouseEntered
        labelEliminarVent.setForeground(new java.awt.Color(255, 90, 0));
        labelVentas.setForeground(new java.awt.Color(255, 90, 0));
        panelVentas.setVisible(true);
    }//GEN-LAST:event_labelEliminarVentMouseEntered

    private void labelEliminarVentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarVentMouseExited
        labelEliminarVent.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelEliminarVentMouseExited

    private void labelIngresarGastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarGastMouseEntered
        labelIngresarGast.setForeground(new java.awt.Color(255, 90, 0));
        labelGastos.setForeground(new java.awt.Color(255, 90, 0));
        panelGastos.setVisible(true);
    }//GEN-LAST:event_labelIngresarGastMouseEntered

    private void labelIngresarGastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarGastMouseExited
        labelIngresarGast.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelIngresarGastMouseExited

    private void labelConsultarGastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarGastMouseEntered
        labelConsultarGast.setForeground(new java.awt.Color(255, 90, 0));
        labelGastos.setForeground(new java.awt.Color(255, 90, 0));
        panelGastos.setVisible(true);
    }//GEN-LAST:event_labelConsultarGastMouseEntered

    private void labelConsultarGastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarGastMouseExited
        labelConsultarGast.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelConsultarGastMouseExited

    private void labelModificarGastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarGastMouseEntered
        labelModificarGast.setForeground(new java.awt.Color(255, 90, 0));
        labelGastos.setForeground(new java.awt.Color(255, 90, 0));
        panelGastos.setVisible(true);
    }//GEN-LAST:event_labelModificarGastMouseEntered

    private void labelModificarGastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarGastMouseExited
        labelModificarGast.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelModificarGastMouseExited

    private void labelEliminarGastMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarGastMouseEntered
        labelEliminarGast.setForeground(new java.awt.Color(255, 90, 0));
        labelGastos.setForeground(new java.awt.Color(255, 90, 0));
        panelGastos.setVisible(true);
    }//GEN-LAST:event_labelEliminarGastMouseEntered

    private void labelEliminarGastMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarGastMouseExited
        labelEliminarGast.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelEliminarGastMouseExited

    private void labelIngresarClieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarClieMouseEntered
        labelIngresarClie.setForeground(new java.awt.Color(255, 90, 0));
        labelClientes.setForeground(new java.awt.Color(255, 90, 0));
        panelClientes.setVisible(true);
    }//GEN-LAST:event_labelIngresarClieMouseEntered

    private void labelIngresarClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarClieMouseExited
        labelIngresarClie.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelIngresarClieMouseExited

    private void labelConsultarClieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarClieMouseEntered
        labelConsultarClie.setForeground(new java.awt.Color(255, 90, 0));
        labelClientes.setForeground(new java.awt.Color(255, 90, 0));
        panelClientes.setVisible(true);
    }//GEN-LAST:event_labelConsultarClieMouseEntered

    private void labelConsultarClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarClieMouseExited
        labelConsultarClie.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelConsultarClieMouseExited

    private void labelModificarClieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarClieMouseEntered
        labelModificarClie.setForeground(new java.awt.Color(255, 90, 0));
        labelClientes.setForeground(new java.awt.Color(255, 90, 0));
        panelClientes.setVisible(true);
    }//GEN-LAST:event_labelModificarClieMouseEntered

    private void labelModificarClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarClieMouseExited
        labelModificarClie.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelModificarClieMouseExited

    private void labelEliminarClieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarClieMouseEntered
        labelEliminarClie.setForeground(new java.awt.Color(255, 90, 0));
        labelClientes.setForeground(new java.awt.Color(255, 90, 0));
        panelClientes.setVisible(true);
    }//GEN-LAST:event_labelEliminarClieMouseEntered

    private void labelEliminarClieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarClieMouseExited
        labelEliminarClie.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelEliminarClieMouseExited

    private void labelIngresarProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarProvMouseEntered
        labelIngresarProv.setForeground(new java.awt.Color(255, 90, 0));
        labelProveedores.setForeground(new java.awt.Color(255, 90, 0));
        panelProveedores.setVisible(true);
    }//GEN-LAST:event_labelIngresarProvMouseEntered

    private void labelIngresarProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarProvMouseExited
        labelIngresarProv.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelIngresarProvMouseExited

    private void labelConsultarProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarProvMouseEntered
        labelConsultarProv.setForeground(new java.awt.Color(255, 90, 0));
        labelProveedores.setForeground(new java.awt.Color(255, 90, 0));
        panelProveedores.setVisible(true);
    }//GEN-LAST:event_labelConsultarProvMouseEntered

    private void labelConsultarProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarProvMouseExited
        labelConsultarProv.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelConsultarProvMouseExited

    private void labelModificarProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarProvMouseEntered
        labelModificarProv.setForeground(new java.awt.Color(255, 90, 0));
        labelProveedores.setForeground(new java.awt.Color(255, 90, 0));
        panelProveedores.setVisible(true);
    }//GEN-LAST:event_labelModificarProvMouseEntered

    private void labelModificarProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarProvMouseExited
        labelModificarProv.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelModificarProvMouseExited

    private void labelEliminarProvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarProvMouseEntered
        labelEliminarProv.setForeground(new java.awt.Color(255, 90, 0));
        labelProveedores.setForeground(new java.awt.Color(255, 90, 0));
        panelProveedores.setVisible(true);
    }//GEN-LAST:event_labelEliminarProvMouseEntered

    private void labelEliminarProvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarProvMouseExited
        labelEliminarProv.setForeground(new java.awt.Color(175, 175, 175));
    }//GEN-LAST:event_labelEliminarProvMouseExited

    private void fondoInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoInicioMouseClicked
        // Oculta paneles que no queden visibles clickeando fuera de ellos y recupera el color de los labels
        panelStock.setVisible(false);
        panelCompras.setVisible(false);
        panelVentas.setVisible(false);
        panelGastos.setVisible(false);
        panelClientes.setVisible(false);
        panelProveedores.setVisible(false);
        labelUsuario.setForeground(new java.awt.Color(255, 180, 140));
        labelStock.setForeground(new java.awt.Color(255, 180, 140));
        labelCompras.setForeground(new java.awt.Color(255, 180, 140));
        labelVentas.setForeground(new java.awt.Color(255, 180, 140));
        labelGastos.setForeground(new java.awt.Color(255, 180, 140));
        labelClientes.setForeground(new java.awt.Color(255, 180, 140));
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140));
        labelReportes.setForeground(new java.awt.Color(255, 180, 140));
        labelAyuda.setForeground(new java.awt.Color(255, 180, 140));
    }//GEN-LAST:event_fondoInicioMouseClicked

    private void labelIngresarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarProdMouseClicked
        new IngresarStock().setVisible(true);
        panelStock.setVisible(false);
        labelStock.setForeground(new java.awt.Color(255, 180, 140));         
    }//GEN-LAST:event_labelIngresarProdMouseClicked

    private void labelConsultarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarProdMouseClicked
        new ConsultarStock().setVisible(true);
        panelStock.setVisible(false);
        labelStock.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelConsultarProdMouseClicked

    private void labelModificarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarProdMouseClicked
        new ModificarStock().setVisible(true);
        panelStock.setVisible(false);
        labelStock.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelModificarProdMouseClicked

    private void labelEliminarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarProdMouseClicked
        new EliminarStock().setVisible(true);
        panelStock.setVisible(false);
        labelStock.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelEliminarProdMouseClicked

    private void labelIngresarCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarCompMouseClicked
        new IngresarCompras().setVisible(true);
        panelCompras.setVisible(false);
        labelCompras.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelIngresarCompMouseClicked

    private void labelConsultarCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarCompMouseClicked
        new ConsultarCompras().setVisible(true);
        panelCompras.setVisible(false);
        labelCompras.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelConsultarCompMouseClicked

    private void labelModificarCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarCompMouseClicked
        new ModificarCompras().setVisible(true);
        panelCompras.setVisible(false);
        labelCompras.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelModificarCompMouseClicked

    private void labelEliminarCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarCompMouseClicked
        new EliminarCompras().setVisible(true);
        panelCompras.setVisible(false);
        labelCompras.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelEliminarCompMouseClicked

    private void labelIngresarVentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarVentMouseClicked
        new IngresarVentas().setVisible(true);
        panelVentas.setVisible(false);
        labelVentas.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelIngresarVentMouseClicked

    private void labelConsultarVentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarVentMouseClicked
        new ConsultarVentas().setVisible(true);
        panelVentas.setVisible(false);
        labelVentas.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelConsultarVentMouseClicked

    private void labelModificarVentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarVentMouseClicked
        new ModificarVentas().setVisible(true);
        panelVentas.setVisible(false);
        labelVentas.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelModificarVentMouseClicked

    private void labelEliminarVentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarVentMouseClicked
        new EliminarVentas().setVisible(true);
        panelVentas.setVisible(false);
        labelVentas.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelEliminarVentMouseClicked

    private void labelIngresarGastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarGastMouseClicked
        new IngresarGastos().setVisible(true);
        panelGastos.setVisible(false);
        labelGastos.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelIngresarGastMouseClicked

    private void labelConsultarGastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarGastMouseClicked
        new ConsultarGastos().setVisible(true);
        panelGastos.setVisible(false);
        labelGastos.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelConsultarGastMouseClicked

    private void labelModificarGastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarGastMouseClicked
        new ModificarGastos().setVisible(true);
        panelGastos.setVisible(false);
        labelGastos.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelModificarGastMouseClicked

    private void labelEliminarGastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarGastMouseClicked
        new EliminarGastos().setVisible(true);
        panelGastos.setVisible(false);
        labelGastos.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelEliminarGastMouseClicked

    private void labelIngresarClieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarClieMouseClicked
        new IngresarClientes().setVisible(true);
        panelClientes.setVisible(false);
        labelClientes.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelIngresarClieMouseClicked

    private void labelConsultarClieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarClieMouseClicked
        new ConsultarClientes().setVisible(true);
        panelClientes.setVisible(false);
        labelClientes.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelConsultarClieMouseClicked

    private void labelModificarClieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarClieMouseClicked
        new ModificarClientes().setVisible(true);
        panelClientes.setVisible(false);
        labelClientes.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelModificarClieMouseClicked

    private void labelEliminarClieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarClieMouseClicked
        new EliminarClientes().setVisible(true);
        panelClientes.setVisible(false);
        labelClientes.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelEliminarClieMouseClicked

    private void labelIngresarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIngresarProvMouseClicked
        new IngresarProveedores().setVisible(true);
        panelProveedores.setVisible(false);
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelIngresarProvMouseClicked

    private void labelConsultarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelConsultarProvMouseClicked
        new ConsultarProveedores().setVisible(true);
        panelProveedores.setVisible(false);
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelConsultarProvMouseClicked

    private void labelModificarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelModificarProvMouseClicked
        new ModificarProveedores().setVisible(true);
        panelProveedores.setVisible(false);
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelModificarProvMouseClicked

    private void labelEliminarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarProvMouseClicked
        new EliminarProveedores().setVisible(true);
        panelProveedores.setVisible(false);
        labelProveedores.setForeground(new java.awt.Color(255, 180, 140)); 
    }//GEN-LAST:event_labelEliminarProvMouseClicked

    private void labelReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelReportesMouseClicked
        new Reportes().setVisible(true);
    }//GEN-LAST:event_labelReportesMouseClicked

    private void labelUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsuarioMouseClicked
        new Usuario().setVisible(true);
    }//GEN-LAST:event_labelUsuarioMouseClicked

    private void labelAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAyudaMouseClicked
        new Ayuda().setVisible(true);
    }//GEN-LAST:event_labelAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoInicio;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JLabel labelAyuda;
    private javax.swing.JLabel labelCerrar;
    private javax.swing.JLabel labelClientes;
    private javax.swing.JLabel labelCompras;
    private javax.swing.JLabel labelConsultarClie;
    private javax.swing.JLabel labelConsultarComp;
    private javax.swing.JLabel labelConsultarGast;
    private javax.swing.JLabel labelConsultarProd;
    private javax.swing.JLabel labelConsultarProv;
    private javax.swing.JLabel labelConsultarVent;
    private javax.swing.JLabel labelEliminarClie;
    private javax.swing.JLabel labelEliminarComp;
    private javax.swing.JLabel labelEliminarGast;
    private javax.swing.JLabel labelEliminarProd;
    private javax.swing.JLabel labelEliminarProv;
    private javax.swing.JLabel labelEliminarVent;
    private javax.swing.JLabel labelGastos;
    private javax.swing.JLabel labelIngresarClie;
    private javax.swing.JLabel labelIngresarComp;
    private javax.swing.JLabel labelIngresarGast;
    private javax.swing.JLabel labelIngresarProd;
    private javax.swing.JLabel labelIngresarProv;
    private javax.swing.JLabel labelIngresarVent;
    private javax.swing.JLabel labelMinimizar;
    private javax.swing.JLabel labelModificarClie;
    private javax.swing.JLabel labelModificarComp;
    private javax.swing.JLabel labelModificarGast;
    private javax.swing.JLabel labelModificarProd;
    private javax.swing.JLabel labelModificarProv;
    private javax.swing.JLabel labelModificarVent;
    private javax.swing.JLabel labelProveedores;
    private javax.swing.JLabel labelReportes;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelVentas;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelCompras;
    private javax.swing.JPanel panelGastos;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelVentas;
    // End of variables declaration//GEN-END:variables
}
